module.exports = {
  api: require('./api.js'),
  deployment: require('./deployment.js'),
  ingress: require('./ingress.js'),
  namespace: require('./namespace.js'),
  pod: require('./pod.js'),
  endpoints: require('./endpoints.js'),
  namespaceCheck: require('./namespaceCheck.js'),
  configMap: require('./configMap.js'),
  secret: require('./secret.js'),
  service: require('./service.js'),
  certificateSigningRequest: require('./certificateSigningRequest.js'),
  clusterRole: require('./clusterRole.js'),
  role: require('./role.js'),
  clusterRoleBinding: require('./clusterRoleBinding.js'),
  roleBinding: require('./roleBinding.js'),
  openapi: require('./openapi.js'),
  node: require('./node.js'),
  serviceAccount: require('./serviceAccount.js'),
  version: require('./version.js'),
  events: require('./events.js'),
};
