// One-off fixer for the broken table() methods generated by templating.js.
// Replaces the shared template's `${plural}.length`/`${plural}[0]`/`${plural}.map`
// references (undefined) with the `items` parameter, and fixes the `/.d{0,3}/`
// regex typo. Run once: `node k82JSHelpfulScripts/fix-stubs.js`.
const fs = require('fs');
const path = require('path');

const objectsDir = path.join(__dirname, '..', 'objects');
const files = fs.readdirSync(objectsDir).filter((f) => f.endsWith('.js'));

let changedCount = 0;
for (const file of files) {
  const full = path.join(objectsDir, file);
  let src = fs.readFileSync(full, 'utf8');
  const orig = src;

  // Only touch files that use the broken template.
  if (!/static async table \(queryOptions = \{\}\)/.test(src)) continue;

  // 1. signature
  src = src.replace(
    /static async table \(queryOptions = \{\}\)/,
    'static async table (items = [])'
  );

  // 2. `${<ident>.length}${JSON.stringify(<sameIdent>[0])}`
  src = src.replace(
    /\$\{([a-zA-Z]+)\.length\}\$\{JSON\.stringify\(\1\[0\]\)\}/,
    '${items.length}${JSON.stringify(items[0])}'
  );

  // 3. `<ident>.map((e) => ({`
  src = src.replace(
    /([a-zA-Z]+)\.map\(\(e\) => \(\{/,
    'items.map((e) => ({'
  );

  // 4. broken regex /.d{0,3}/ -> /\.\d{0,3}/
  src = src.replace(/\/\.d\{0,3\}\//g, '/\\.\\d{0,3}/');

  if (src !== orig) {
    fs.writeFileSync(full, src);
    changedCount++;
    console.log(`fixed ${file}`);
  }
}
console.log(`\n${changedCount} files updated.`);
